[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day01"
src = "src/bin"
[[bin]]
name = "day02"
src = "src/bin"
[[bin]]
name = "day03"
src = "src/bin"

[dependencies]
